- content/developers/internals/simulation-model/_index.md
- content/developers/internals/simulation-model/location.md
- content/developers/internals/simulation-model/movable-elements.md
- content/developers/internals/simulation-model/ordering.md
- content/developers/internals/simulation-model/reservation.md
- content/developers/internals/simulation-model/routing.md
- content/developers/internals/simulation-model/signaling.md
- content/developers/internals/simulation-model/spacing.md
Following discussion with Christophe Mémin, the following changes were implemented:
- the definition of the reservation state of zones was changed
- the definition of routes was changed
- the requirements for routes were changed
- the concept of route entry was removed in favor of relying on zone states
- the definition of spacing signaling route was changed: they now truly have no state, even temporary
- operations were added to the spacing layer
- general consistency work was undertaken
> Update the simulation model

- content/docs/guides/contribute/bug-reports.en.md
- content/docs/guides/contribute/code.en.md
- content/docs/guides/contribute/conventions.en.md
Moving part of https://github.com/DGEXSolutions/osrd/pull/3347 in `conventions` file and completing current `contribute` pages.
:warning: I will do the translation in french once we are ok with the content :warning:
> contribute: Update contribute pages and add conventions

- content/docs/explanation/models/data-models-full-example/index.fr.md
Some broken links discovered when I browsed the documentation.
> docs: fix image and URL links

- content/docs/explanation/containers-architecture/_index.en.md
- content/docs/explanation/containers-architecture/_index.fr.md
- content/docs/guides/deploy/_index.en.md
- content/docs/guides/deploy/_index.fr.md
- content/docs/guides/deploy/docker-compose/_index.en.md
- content/docs/guides/deploy/docker-compose/_index.fr.md
- content/docs/guides/deploy/kubernetes/_index.en.md
- content/docs/guides/deploy/kubernetes/_index.fr.md
This modification add guides that cover deployments
> guides: deployment

- content/docs/explanation/models/data-models-full-example/index.en.md
- content/docs/explanation/models/data-models-full-example/index.fr.md
also some automatic formating from editor
> docs: small fixes on ambiguity and french

- .github/workflows/code_quality.yml
This will enforce common format for titles.
This will also avoid `fixup!` `squash!` and `amend!` (autosquash) commits.
Inspired from osrd-project/osrd#6484
> ci: check commit titles

- .github/scripts/check-commit-titles.sh
- .github/workflows/code_quality.yml
- content/docs/guides/contribute/contribute-code/commit-style.en.md
- content/docs/guides/contribute/contribute-code/commit-style.fr.md
also port last check of commit after ~https://github.com/osrd-project/osrd/pull/6557~ https://github.com/osrd-project/osrd/pull/6580
TODO:
> doc, ci: precise commit style

- content/docs/guides/contribute/contribute-code/general-principles.en.md
- content/docs/guides/contribute/contribute-code/general-principles.fr.md
- content/docs/guides/contribute/license-and-set-up.en.md
- content/docs/guides/contribute/license-and-set-up.fr.md
Details for editoast are moved close to the code, in `osrd/editoast/README.md` (see https://github.com/osrd-project/osrd/pull/6762).
Follow-up on https://github.com/osrd-project/osrd-website/pull/154#pullrequestreview-1865252374
> doc: move dependencies bump batching in general principles

- content/docs/guides/contribute/contribute-code/frontend-conventions.en.md
- content/docs/guides/contribute/contribute-code/frontend-conventions.fr.md
Update guidelines after recent updates on front type imports and imports order
> doc: update front guidelines for imports

- content/docs/reference/design-docs/timetable/index.en.md
> design-docs: add a 'arrival-on-stop-signal' flag for timetable

- content/docs/reference/design-docs/timetable/index.en.md
As discussed (at least with @eckter @multun), the flag's name is shortened.
Follow-up on https://github.com/OpenRailAssociation/osrd-website/pull/189
> design-doc: rename (shorten) 'on_stop_signal' flag for timetable

- content/docs/reference/design-docs/train-sim-v3/driver-behavior-modules.en.md
- content/docs/reference/design-docs/train-sim-v3/overshoot.svg
> try explaining driver behaviors

- content/docs/reference/design-docs/train-sim-v3/_index.en.md
> add concepts for train-sim v3

- content/docs/reference/design-docs/train-sim-v3/overview.en.md
> Add a generalistic description

- content/docs/reference/design-docs/train-sim-v3/_index.en.md
- content/docs/reference/design-docs/train-sim-v3/driver-behavior-modules.en.md
- content/docs/reference/design-docs/train-sim-v3/driving-instruction.en.md
- content/docs/reference/design-docs/train-sim-v3/overshoot.svg
- content/docs/reference/design-docs/train-sim-v3/overview.en.md
- content/docs/reference/design-docs/train-sim-v3/overview.svg
- content/docs/reference/design-docs/train-sim-v3/prior-art.en.md
- content/docs/reference/design-docs/train-sim-v3/reconciliation.svg
<details>
<summary>Réunion du 24/01/2024, notes de @clarani</summary>
---
Quels sont les objectifs de la journée ? Design les nouvelles API du calcul de marche
Quelles contraintes ?
→ pouvoir gérer des contraintes bornées dans le temps (temps système, réaction signalisation)
→ pouvoir rajouter des contraintes dynamiquement, ce qui permettra de faire de la simulation multitrains
---
Caractéristiques du modèle actuel
→ l’état du train se résume à un couple position/vitesse uniquement à un point de la courbe
→ le calcul de marche est calculé par morceaux, mais pas d’une manière non causale
→ recollage un peu bancal entre les morceaux
→ backtracking pour les marges
Quels sont les problèmes du modèle actuel ?
→ impossible d’ajouter des paramètres supplémentaires comme l’état d’une batterie, un …
> docs: design doc for the revamp of the running time calculation

- content/docs/reference/apis/_index.en.md
- content/docs/reference/apis/editoast.md
- content/docs/reference/apis/gateway.md
- layouts/page/swagger-ui.html
It seems like the APIs section has been removed in 3de3e8c95c73. However I found it quite handy to be able to quickly access a webpage describing the API.
It appears like there were two issues with the previous approach: the OpenAPI schema was locally duplicated (making it often times outdated and cumbersome to keep in sync), and the swagger-ui integration needed a dedicated Hugo plugin.
Directly download the OpenAPI schema from GitHub instead of keeping a copy, and use a HTML template for swagger-ui instead of a plugin. This should make it easier to maintain.
* * *
Is this an acceptable approach? Were there other reasons why the APIs section has been dropped in the first place?
> Re-introduce APIs section

- content/docs/reference/design-docs/timetable/index.en.md
The margin example was invalid
> docs: fix timetable v2 margin example

- .github/workflows/gh-pages.yml
We are not using the static built json schema files anymore. (Removed [here](https://github.com/OpenRailAssociation/osrd-website/commit/3de3e8c95c73d4b0e18f13e252cb319189838ee4))
> ci: remove unused railjson schema

- content/docs/reference/design-docs/auth/_index.en.md
- content/docs/reference/design-docs/timetable/index.en.md
Different forums agree that one should write "a user" rather than "an user", and in the [cambridge dictonnary's page for user](https://dictionary.cambridge.org/dictionary/english/user), one can find 4 occurences of "a user" and no occurrence of "an user".
> docs: replace occurrences of "an user" with "a user"

- content/docs/reference/design-docs/timetable/index.en.md
Replace on_stop_signal flag by reception_signal enum
Prepares https://github.com/OpenRailAssociation/osrd/issues/8809
> doc: allow specifying short slip distance in train-schedule

- content/docs/reference/design-docs/timetable/index.en.md
- ... **we** do not want to **lose** ...
https://www.merriam-webster.com/grammar/lose-vs-loose-usage
- the back-end run**s** ...
- ... makes no **practical** sense ...
- ... was **chosen**, ...
https://www.merriam-webster.com/dictionary/choosen
- Incon**sis**tent train schedule
- ... ackno**w**ledge the change
- inferred
https://www.merriam-webster.com/dictionary/infered
- ... cases **where** a movable ...
- there **must** be ...
- partiti**one**d ...
https://www.merriam-webster.com/dictionary/partitionned
- **hundreds** of trains
- it can **take** some time
> docs: timetable fix spelling and grammar

- content/about/roadmap.en.md
- content/about/roadmap.fr.md
This is to fix the following comment: https://github.com/OpenRailAssociation/technical-committee/pull/190#discussion_r1923445268
> Roadmap add link to project boards

- content/docs/reference/design-docs/timetable/index.en.md
Few information about paced trains.
> add paced trains documentation

- .github/workflows/code_quality.yml
Switch to [streetsidesoftware/cspell-action][1] so that:
- Spelling errors are not fatal
- Spelling errors are reported inline
[1]: https://github.com/streetsidesoftware/cspell-action
> github: switch to cspell action, warn about changed files only

- layouts/page/swagger-ui.html
Seems like "Params.params" doesn't exist anymore. Use the "Param" (singular) function instead:
https://gohugo.io/methods/page/param/
> docs: fix REST API docs

- content/docs/reference/design-docs/timetable/index.en.md
Fix Paced train documentation in Timetable V2
> timetable_v2: fix paced train documentation
