content/developers/internals/internals/interlocking.md
it will get translated to english once it's less drafty
=> interlocking: draft the new signaling and routing APIs

content/developers/internals/quality/_index.md
First draft. thanks to provide constructive feedback.
=> doc: add built-in quality page

.github/workflows/gh-pages.yml, content/who-we-are/project/short-term-dcm.md
Reverts DGEXSolutions/osrd-website#54
=> Revert "testing new CI directory "

content/docs/guides/contribute/bug-reports.fr.md, content/docs/guides/contribute/code.fr.md, content/docs/guides/contribute/conventions.en.md, content/docs/guides/contribute/conventions.fr.md
=> contribute: Add and update french translations

content/blog/news/2023/opendata-fosdem.en.md
Add a new link to the updated version of data + comment on what's changed
=> Update data file

config/_default/config.toml
=> config: fix page source edit / view

content/_index.en.html, content/about/governance/index.en.md, content/about/governance/index.fr.md
I don’t why there is a commit on home page _index.en.html included in this PR. I will revert the changes shown here as there are already included in the PR #109.
=> Governance/index (en + fr)

README.md, config/_default/config.toml, content/_index.en.html, content/_index.fr.html, content/about/opensource.en.md, content/about/opensource.fr.md, content/blog/news/2023/morganepostlinkedin.fr.md, content/blog/news/2023/post_linkedin_morgane/index.en.md, content/blog/news/2023/post_linkedin_morgane/index.fr.md, content/docs/explanation/data-model/index.en.md, content/docs/explanation/data-model/index.fr.md, content/docs/explanation/running_time_calculation/numerical_integration.en.md, content/docs/explanation/running_time_calculation/numerical_integration.fr.md, content/docs/guides/contribute/_index.en.md, content/docs/guides/contribute/_index.fr.md, content/docs/guides/contribute/bug-reports.en.md, content/docs/guides/contribute/bug-reports.fr.md, content/docs/guides/contribute/code.en.md, content/docs/guides/contribute/code.fr.md, content/docs/guides/contribute/conventions.en.md, content/docs/guides/contribute/conventions.fr.md, content/docs/reference/design-docs/stdcm/pathfinding_module/implementation_details.en.md, content/docs/reference/design-docs/stdcm/pathfinding_module/implementation_details.fr.md, package.json
The project migrated from the DGEXSolutions org to osrd-project
=> update all github links

content/docs/reference/design-docs/conflict-detection/index.en.md, content/docs/reference/design-docs/conflict-detection/requirements-diagram.html, content/docs/reference/design-docs/conflict-detection/requirements-diagram.svg
- switch to a simpler requirement model
- describe incremental requirement generation
- describe the schema of spacing and routing requirements
- rebrand the conflict diagram as a requirement diagram, show margins by default
=> docs: update conflict detection documentation

content/docs/guides/contribute/code.en.md, content/docs/guides/contribute/code.fr.md
Mention WSL and Docker Desktop
=> content: clarify code contribution guide

content/about/governance/index.en.md, content/about/governance/index.fr.md
=> Màj financeurs

assets/scss/_variables_project.scss
=> theme: disable gradients and shadows

content/docs/explanation/models/data-models-full-example/index.en.md, content/docs/explanation/models/data-models-full-example/index.fr.md, content/docs/railway-wiki/glossary/_index.fr.md
=> doc: add french "point remarquable"

content/docs/guides/contribute/conventions/front.en.md, content/docs/guides/contribute/conventions/front.fr.md
=> doc: css modules guide

content/docs/reference/design-docs/timetable/index.en.md
This doc comes from this issue: https://github.com/OpenRailAssociation/osrd/issues/8055
=> docs: add timetablev2 frontend workflow

content/about/opensource.en.md
according to
https://www.merriam-webster.com/dictionary/chosen
https://www.merriam-webster.com/dictionary/developed
https://www.merriam-webster.com/dictionary/database
and
https://www.merriam-webster.com/dictionary/open-source
Note: 
open-source as an adjective , with hyphen
Open Source as a noun, without hyphen
=> Update opensource.en.md, spelling

content/docs/explanation/netzgrafik-editor/_index.en.md
- developed
- through a proof of concept
- an operational ...
- has been abandoned ...
- level of detail
- refactoring
- functionalities
- management, versioning
- diagram shows ...
- the very last ...
- transforms ...
=> fix: doc: netzgrafik editor spelling grammar

content/docs/explanation/running_time_calculation/numerical_integration.en.md
- Disadvantages of ...
- in French
see also:
https://www.merriam-webster.com/dictionary/french
=> fix: doc: numerical_integration.en.md, spelling, uppercase

content/docs/explanation/running_time_calculation/physical_modeling.fr.md
=> fix: doc: physical_modeling.fr.md missing accent

content/docs/guides/contribute/code-review.en.md, content/docs/guides/contribute/code-review.fr.md, content/docs/guides/contribute/contribute-code/share-changes.en.md, content/docs/guides/contribute/contribute-code/share-changes.fr.md, content/docs/guides/contribute/review-process.en.md, content/docs/guides/contribute/review-process.fr.md
- Add details on the use of github notifications
=> Update review process

content/docs/reference/design-docs/auth/_index.en.md
See https://github.com/OpenRailAssociation/osrd/pull/9602 for context.
=> design-docs: fix the headers for authn

content/docs/reference/design-docs/stdcm/pathfinding_module/implementation_details.en.md
The classes mentionned in this file got rewritten in Kotlin. Update the resulting broken links and method signatures.
=> doc: implementation_details: update links and method signatures

content/about/governance/index.en.md
- develo**p**er developed
- commi**tt**ed
- organi**z**ation (to be consistent with _organize_ further in the en file)
see:
https://www.merriam-webster.com/dictionary/developped
https://www.merriam-webster.com/dictionary/developper
https://www.merriam-webster.com/dictionary/commited
https://www.merriam-webster.com/dictionary/organisation
=> doc: governance fix spelling

.github/workflows/gh-pages.yml, README.md, content/_index.en.html, content/_index.fr.html, go.mod, go.sum, hugo.sh, hugo.toml, package.json
_See individual commits._
Fixes the build with more recent hugo versions:
- https://github.com/google/docsy/issues/1930
- https://github.com/google/docsy/issues/2176
=> Upgrade docsy and hugo

content/docs/guides/contribute/contribute-code/share-changes.en.md, content/docs/guides/contribute/contribute-code/share-changes.fr.md
A proposition to add a bit more precisions about the size of Pull Requests.
=> docs: add precisions about big PR

content/docs/guides/contribute/review-process.en.md, content/docs/guides/contribute/review-process.fr.md
Anyone can merge the PR once approved (with a preference for the author).
=> docs: fix review process
